// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0jju0IHWRnBsE7zGGh3hlzUp3aoPx00M',
    appId: '1:1098360809704:web:8f8bcbc2b511cf81e8415d',
    messagingSenderId: '1098360809704',
    projectId: 'xchangehub-f61be',
    authDomain: 'xchangehub-f61be.firebaseapp.com',
    databaseURL: 'https://xchangehub-f61be-default-rtdb.firebaseio.com',
    storageBucket: 'xchangehub-f61be.firebasestorage.app',
    measurementId: 'G-02WK6JWK0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDBrISJPedZDogvuHuqNNSLWo58qpEUQ',
    appId: '1:1098360809704:android:10d8097f88e1f009e8415d',
    messagingSenderId: '1098360809704',
    projectId: 'xchangehub-f61be',
    databaseURL: 'https://xchangehub-f61be-default-rtdb.firebaseio.com',
    storageBucket: 'xchangehub-f61be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvi7b21LQiYWeis0lsY6jgdqXXdG9ZUbY',
    appId: '1:1098360809704:ios:7247b97753171948e8415d',
    messagingSenderId: '1098360809704',
    projectId: 'xchangehub-f61be',
    databaseURL: 'https://xchangehub-f61be-default-rtdb.firebaseio.com',
    storageBucket: 'xchangehub-f61be.firebasestorage.app',
    iosBundleId: 'com.xchangehub.xchangehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvi7b21LQiYWeis0lsY6jgdqXXdG9ZUbY',
    appId: '1:1098360809704:ios:7247b97753171948e8415d',
    messagingSenderId: '1098360809704',
    projectId: 'xchangehub-f61be',
    databaseURL: 'https://xchangehub-f61be-default-rtdb.firebaseio.com',
    storageBucket: 'xchangehub-f61be.firebasestorage.app',
    iosBundleId: 'com.xchangehub.xchangehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0jju0IHWRnBsE7zGGh3hlzUp3aoPx00M',
    appId: '1:1098360809704:web:c93434cb1e1c56d7e8415d',
    messagingSenderId: '1098360809704',
    projectId: 'xchangehub-f61be',
    authDomain: 'xchangehub-f61be.firebaseapp.com',
    databaseURL: 'https://xchangehub-f61be-default-rtdb.firebaseio.com',
    storageBucket: 'xchangehub-f61be.firebasestorage.app',
    measurementId: 'G-846QSRXDSR',
  );
}
